# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json* ./

# Install dependencies (skip scripts to speed up build if needed)
RUN npm install --ignore-scripts

# Copy remaining source code
COPY . .

# Build the project
RUN npm run build

# Expose port if needed (not required for MCP using stdio, but helpful for debugging)
# EXPOSE 3000

# Command to run the MCP server
CMD ["node", "dist/index.js"]
